export { default as productsRouter } from "./products.route.js";
export { default as customersRouter } from "./customers.route.js";
export { default as departmentsRouter } from "./departments.route.js";
export { default as employeesRouter } from "./employees.route.js";
export { default as suppliersRouter } from "./suppliers.route.js";
export { default as shipmentsRouter } from "./shipments.route.js";
export { default as employeePayrollsRouter } from "./employee_payrolls.route.js";
export { default as monthlyPayrollsRouter } from "./monthly_payrolls.route.js";
export { default as authRouter } from "./auth.route.js";